"""Add Hungry Games tables.

Deliberately hand-written rather than autogenerated. Autogenerate also proposed
renaming several CHECK constraints created by 0001 — naming-convention drift
between that migration and the models, unrelated to this change. Applying those
would churn constraints on a live database for no benefit, so only the new
tables are included here.

Revision ID: 0002_hungry_games
Revises: 0001_initial_economy
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0002_hungry_games"
down_revision = "0001_initial_economy"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "games",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("entry_fee", sa.BigInteger(), nullable=False),
        sa.Column("seeded_pot", sa.BigInteger(), nullable=False),
        sa.Column("min_players", sa.Integer(), nullable=False),
        sa.Column("signup_closes_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_tick_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('signup', 'running', 'complete', 'cancelled')",
            name="ck_games_status_valid",
        ),
        sa.CheckConstraint("entry_fee >= 0", name="ck_games_entry_fee_nonnegative"),
        sa.CheckConstraint("seeded_pot >= 0", name="ck_games_seeded_pot_nonnegative"),
        sa.CheckConstraint("min_players >= 2", name="ck_games_min_players_sane"),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_settings.guild_id"],
            name="fk_games_guild_id_guild_settings",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_games"),
    )
    op.create_index("ix_games_guild_id", "games", ["guild_id"])
    op.create_index("ix_games_status", "games", ["status"])
    op.create_index("ix_games_next_tick_at", "games", ["next_tick_at"])

    # At most one open or running game per guild. Enforced by the database so
    # two people starting a game at the same moment cannot both succeed.
    op.create_index(
        "uq_games_one_active_per_guild",
        "games",
        ["guild_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('signup', 'running')"),
    )

    op.create_table(
        "game_participants",
        sa.Column("game_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("alive", sa.Boolean(), nullable=False),
        sa.Column("eliminated_round", sa.Integer(), nullable=True),
        sa.Column("placement", sa.Integer(), nullable=True),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name="fk_game_participants_game_id_games", ondelete="CASCADE"
        ),
        # Keyed on the account, so a member leaving the server is removed by the
        # same cascade that deletes the rest of their economy data.
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["economy_accounts.id"],
            name="fk_game_participants_account_id_economy_accounts",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("game_id", "account_id", name="pk_game_participants"),
    )


def downgrade() -> None:
    op.drop_table("game_participants")
    op.drop_index("uq_games_one_active_per_guild", table_name="games")
    op.drop_index("ix_games_next_tick_at", table_name="games")
    op.drop_index("ix_games_status", table_name="games")
    op.drop_index("ix_games_guild_id", table_name="games")
    op.drop_table("games")
